<a href="https://colab.research.google.com/github/chw8207/data/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 깃허브 설정

In [1]:
cd /content/drive/MyDrive/Colab Notebooks/데이터분석

/content/drive/MyDrive/Colab Notebooks/데이터분석


In [2]:
!git clone https://chw8207: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@github.com/chw8207/data.git

Cloning into 'data'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (3/3), done.


In [4]:
import numpy as np

### 넘파이 배열

In [5]:
# 유사 배열 객체를 넘파이 배열로 변환
arr1 = np.array([0,2,5.5,7])
print(arr1)

[0.  2.  5.5 7. ]


In [6]:
# 2차원 배열 생성하기
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

- 넘파이 배열 생성 함수

In [7]:
# 0으로 채워지는 배열
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [8]:
# 타입 확인
type(arr)

numpy.ndarray

In [9]:
# 크기 확인
arr.shape

(5,)

In [10]:
# 데이터 타입
arr.dtype

dtype('float64')

In [14]:
# 배열 초기화
arr = np.zeros(shape=(6,2))

# 값 채우기
for i in range(6) :
  arr[i] = (i,i)

arr

array([[0., 0.],
       [1., 1.],
       [2., 2.],
       [3., 3.],
       [4., 4.],
       [5., 5.]])

In [15]:
# 값이 1로 채워지는 배열
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.ones((5,), dtype=int)

array([1, 1, 1, 1, 1])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
# 데이터타입 확인
arr.dtype

dtype('float64')

In [19]:
# empty(): 초기화되지 않은 임의의 값들을 생성
np.empty((2,2))

array([[0. , 2. ],
       [5.5, 7. ]])

In [20]:
np.empty((2,2), dtype=int)

array([[                  0, 4611686018427387904],
       [4617878467915022336, 4619567317775286272]])

In [22]:
# eye(): 대각선은 1 그 밖의 위치에 값 0을 지정하는 함수
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [23]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [24]:
np.eye(3, k=-2)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.]])

In [26]:
# linespace: 명시된 간격으로 균등하게 분할된 값 반환
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [28]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

- 배열 생성 함수(np.arange())

In [29]:
# 1차원 배열 생성하기
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [30]:
arr.shape

(5,)

In [31]:
np.arange(3,7)

array([3, 4, 5, 6])

In [32]:
np.arange(3,9,2)

array([3, 5, 7])

In [33]:
# 넘파이 배열 값 변경하기
arr[2] = 10
arr

array([ 0,  1, 10,  3,  4])

In [34]:
# 동종 배열(homogeneous array)
arr[3] = 'jin'

ValueError: ignored

In [36]:
# reshape(): 2차원 배열을 생성할 수 있음.
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
arr.shape

(3, 4)

In [38]:
# 다차원 배열을 1차원으로 변경하기
arr.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [39]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [40]:
arr.reshape(-1,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [42]:
arr.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
# 3차원 배열 생성하기
arr = np.arange(24).reshape(2,3,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

- 넘파이 ndarray 클래스